name: D-Whook
version: '1.0.1'
main: io.github.haburashi76.d_whook.DWhookPlugin
api-version: '1.21'
commands:
  dwhook:
    permission: io.github.haburashi76.dwhook
permissions:
  io.github.haburashi76.dwhook:
    default: op
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0